### ISSUE TITLE
Can't it open files?

### ISSUE THREAD

**Issue by jsmm** [jfcherng-sublime/ST-OpenUri#1]
This is a nice plugin, but is it working for files? Neither with the `@default` nor with the `@custom` regex I have tried:

```
"@custom": "(([^\\s\\\"]+(\\s[^\\s\\\"])*)+)",

 "file://": {"enabled": true, "path_regex": "@custom"},
```
I'm using Sublime Text 3.2.2.

**Comment by jfcherng** [comment]
This plugin only "open" clicked the scheme URI. As for what will happen after clicking, that depends on what's registered for the URI on your operating system, not related to this plugin.

**Comment by jsmm** [comment]
The issue is that OpenUri doesn’t find *file://* paths; therefore, it doesn’t draw a phantom, nor does it make the path clickable in order to open the file with whatever app.

It does work with _http, mailto_, etc. But it doesn’t with _file://_, even when changing from the default to a custom regex.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/71759931-5b7a6c80-2ef0-11ea-8d73-2f2dee8dacb6.png)

I tried the above two cases, the upper (URL-encoded) one is not working. But the latter one gets opened in Sublime Text in a new tab. Is this what you encountered too?

**Comment by jsmm** [comment]
I have applied your fix. Yet files in macOS are not detected:

![Captura de pantalla 2020-01-04 a las 9 07 43](https://user-images.githubusercontent.com/2811090/71762640-16474200-2ed2-11ea-8c22-eec024118e6f.png)

Thanks for your reply.

**Comment by jfcherng** [comment]
There is a problem in your custom regex which causes all previous text are matched as a whole across lines.
```
"@custom": "(([^\\s\\\"]+(\\s[^\\s\\\"])*)+)",
                          ^^^ why?
```

**Comment by jsmm** [comment]
I have restarted ST several times since. As for the regex, thanks for the observation but it is copied from the Open URL plugin and it works well with it. 

From your image captures I understand you use Windows, and I don’t know if OpenUri opens files for other macOS users. It seems difficult to pinpoint the problem, so I will leave it as it is. Thanks for your attention.

**Comment by jfcherng** [comment]
I have a Ubuntu VM but still not reproduce your problem. The URI should be recognized at least but, in your screenshot,  they weren't. So it's not even a problem about how they are opened.

Currently, I do not see a bug at this point.

**Comment by jfcherng** [comment]
You may paste the *whole* settings file for this plugin if you don't mind.

**Comment by jfcherng** [comment]
Close due to inactivity.
