### ISSUE TITLE
Constantly calling sublime.load_settings

### ISSUE THREAD

**Issue by rchl** [jfcherng-sublime/ST-OpenUri#2]
This package is calling `sublime.load_settings` from some interval every second or so. That shouldn't be necessary.

(I haven't checked which code does it exactly).

**Comment by jfcherng** [comment]
Just wonder does it cause performance degradation?

There is `Subsequent calls to load_settings() with the base_name will return the same object, and not load the settings from disk again.` from the official docs of `sublime.`load_settings()` so I guess I thought that's fine.

**Comment by rchl** [comment]
I haven't noticed any performance issues. Only noticed this because I've logged the API when investigating a bug and this one was very noisy.

**Comment by jfcherng** [comment]
> I haven't noticed any performance issues. Only noticed this because I've logged the API when investigating a bug and this one was very noisy.

Should've been fixed in 4c10b9132adf6f8a85799ba05f57baabcc808aaf. I will release a new version within hours :D

**Comment by rchl** [comment]
Nice. Thanks. 👍
